//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string EditListDescriptLable {
            get {
                return ResourceManager.GetString("EditListDescriptLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EditListNameLable {
            get {
                return ResourceManager.GetString("EditListNameLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EditListNamePplace {
            get {
                return ResourceManager.GetString("EditListNamePplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string EditListNickLable {
            get {
                return ResourceManager.GetString("EditListNickLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string EditListNickPlace {
            get {
                return ResourceManager.GetString("EditListNickPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string EditListTitle {
            get {
                return ResourceManager.GetString("EditListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and NickName must be fiiled.
        /// </summary>
        internal static string EditPrifileError {
            get {
                return ResourceManager.GetString("EditPrifileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string MainListAddProffButton {
            get {
                return ResourceManager.GetString("MainListAddProffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string MainListMenuItemDelete {
            get {
                return ResourceManager.GetString("MainListMenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string MainListMenuItemEdit {
            get {
                return ResourceManager.GetString("MainListMenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added.
        /// </summary>
        internal static string MainListNoProfAddedLable {
            get {
                return ResourceManager.GetString("MainListNoProfAddedLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILES.
        /// </summary>
        internal static string MainListTitle {
            get {
                return ResourceManager.GetString("MainListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SetViewLanguageEnLable {
            get {
                return ResourceManager.GetString("SetViewLanguageEnLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings.
        /// </summary>
        internal static string SetViewLanguageLable {
            get {
                return ResourceManager.GetString("SetViewLanguageLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string SetViewLanguageRusLable {
            get {
                return ResourceManager.GetString("SetViewLanguageRusLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by date of creation.
        /// </summary>
        internal static string SetViewSortByDateLable {
            get {
                return ResourceManager.GetString("SetViewSortByDateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by name.
        /// </summary>
        internal static string SetViewSortByNameLable {
            get {
                return ResourceManager.GetString("SetViewSortByNameLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by nickname.
        /// </summary>
        internal static string SetViewSortByNickNameLable {
            get {
                return ResourceManager.GetString("SetViewSortByNickNameLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort profiles list.
        /// </summary>
        internal static string SetViewSortLable {
            get {
                return ResourceManager.GetString("SetViewSortLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SetViewTitle {
            get {
                return ResourceManager.GetString("SetViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInBtnLogin {
            get {
                return ResourceManager.GetString("SignInBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        internal static string SignInLabelSignUp {
            get {
                return ResourceManager.GetString("SignInLabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SignInLoginPlaceHolder {
            get {
                return ResourceManager.GetString("SignInLoginPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignInPasPlaceHolder {
            get {
                return ResourceManager.GetString("SignInPasPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSignIn.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string SignUpButtonSigUp {
            get {
                return ResourceManager.GetString("SignUpButtonSigUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        internal static string SignUpConfirmPass {
            get {
                return ResourceManager.GetString("SignUpConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SignUpLoginPlace {
            get {
                return ResourceManager.GetString("SignUpLoginPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUpPassPlace {
            get {
                return ResourceManager.GetString("SignUpPassPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUpView.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
    }
}
